### PR TITLE
Removed nature spring as sponsor

### PR DESCRIPTION
**Pull request by juvarabrera**

### CODE REVIEW

**Comment by juvarabrera** [comment]
Revert. AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH @tjmonsi

**Comment by tjmonsi** [comment]
Just revert

**Comment by tjmonsi** [comment]
@juvarabrera what do you need?

**Comment by juvarabrera** [comment]
Bring back nature spring as sponsor

**Pull request merged**
